apiVersion: v2
appVersion: "1.0"
description: A Helm chart for {{ cookiecutter.product }}-{{ cookiecutter.component_id }} App
name: {{ cookiecutter.product }}-{{ cookiecutter.component_id }}
home: https://github.com/hmcts/{{ cookiecutter.product }}-{{ cookiecutter.component_id }}
version: 0.0.1
maintainers:
  - name: HMCTS {{ cookiecutter.product }} team
dependencies:
  - name: java
    version: 3.6.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
